//! Raw bindings to the functions exported by the WHY2025 badge
//!
//! ## Example
//!
//! ```rust
//! #![no_std]
//!
//! unsafe {
//!     why2025_badge_sys::printf(b"Hello, world!\n\0".as_ptr());
//! }
//! ```
//!
//! The bindings are autogenerated from the headers present in the firmware, so they are not exactly idiomatic rust.
//!
//! The symbols definitely need more documentation. If you want to add some, please add it to the C code in the firmware repository, it will get picked up when rebuilding lib.rshift
//!
//! ## Interesting symbols
//!
//! * [printf]
//! * [window_create]
//! * [window_framebuffer_create]
//! * [window_present]

#![no_std]
#![allow(nonstandard_style)]
#![allow(non_camel_case_types)]

mod bindings;
mod types;

pub use bindings::*;
pub use types::*;
