[target.riscv32imafc-unknown-none-elf]
rustflags = [
	"-Crelocation-model=pic",
]

[alias]
badge-check = ["check", "--target", "riscv32imafc-unknown-none-elf", "-Zbuild-std=core,alloc,compiler_builtins"]
badge-build = ["build", "--target", "riscv32imafc-unknown-none-elf", "-Zbuild-std=core,alloc,compiler_builtins"]
badge-run = ["run", "--target", "riscv32imafc-unknown-none-elf", "-Zbuild-std=core,alloc,compiler_builtins"]
emu-check = ["check", "--target", "x86_64-unknown-linux-gnu"]
emu-build = ["build", "--target", "x86_64-unknown-linux-gnu"]
emu-run = ["run", "--target", "x86_64-unknown-linux-gnu"]
