[alias]
badge-check = ["check", "--target", "riscv32imafc-unknown-badgevms"]
badge-build = ["build", "--target", "riscv32imafc-unknown-badgevms"]
badge-run = ["run", "--target", "riscv32imafc-unknown-badgevms"]
emu-check = ["check", "--target", "x86_64-unknown-linux-gnu"]
emu-build = ["build", "--target", "x86_64-unknown-linux-gnu"]
emu-run = ["run", "--target", "x86_64-unknown-linux-gnu"]
emu-abi-check = [
	"check",
	"-p",
	"why2025-badge-emu-abi",
	"--target",
	"x86_64-unknown-linux-gnu",
]
emu-abi-build = [
	"build",
	"-p",
	"why2025-badge-emu-abi",
	"--target",
	"x86_64-unknown-linux-gnu",
]
emu-abi-test = [
	"test",
	"-p",
	"why2025-badge-emu-abi",
	"--lib",
	"--target",
	"x86_64-unknown-linux-gnu",
]
